### ISSUE TITLE
Prestige, Piety, and Money displayed increased over game in CK3 1.5

### ISSUE THREAD

**Issue by awbooze** [crschnick/pdx_unlimiter#75] opened 2022-02-09 06:11 UTC
## Description

Pdx-Unlimiter displays the Ironman save I've imported from Crusader Kings version 1.5 with massively overinflated values for prestige, 
piety, men at arms, and money. It looks like it might be multiplying them by 100, except for the amount of money I currently have, which is only multiplied by two or three.

## Images
![image](https://user-images.githubusercontent.com/42682253/153130884-fa7c46eb-54d0-4294-af55-22396eeb56c4.png)

![image](https://user-images.githubusercontent.com/42682253/153130941-6f0de005-3369-42c9-8505-96d246a032ff.png)

**Comment by crschnick** [comment] 2022-02-09 09:54
That is an issue caused by the fact that the Ironman converter is not ready for 1.5 yet. They probably changed the format of these entries in 1.5

**Comment by crschnick** [comment] 2022-02-11 17:12
With the latest release this problem has been fixed for 1.5 saves but had to be introduced for <= 1.4 saves instead to get the Ironman converter running.

**Comment by crschnick** [comment] 2022-05-26 18:16
Fixed in the latest pre-release

**Closed by crschnick** 2022-05-26 18:16 UTC
