### ISSUE TITLE
Update moved install location

### ISSUE THREAD

**Issue by joelproko** [crschnick/pdx_unlimiter#36] opened 2021-02-21 08:15 UTC
I had PDX Unlimiter installed under D:\ProgramsHDD\

When PDX Unlimiter asked to update just now, I was first surprised that it asked for Admin confirmation, given that the folder it was in is in userland, and then after the install it was no longer there, but in C:\Program Files\ instead.

Also, it added a Desktop shortcut without asking.

**Comment by crschnick** [comment] 2021-02-21 10:01
Yeah the update with Admin confirmation was a Pdx-Unlimiter launcher update, which is needed so that the Eu4SaveEditor can now also be updated automatically when enabled.

In theory it should update the installation at the existing location, so something went wrong there. I will take a look at that.

I will also take a look at the Desktop icon.

**Comment by crschnick** [comment] 2021-02-21 16:33
Ok I found the cause for that, so I am trying my best to fix it

**Comment by crschnick** [comment] 2021-02-22 11:05
This should be fixed now.

However, since your installation is now in the wrong directory, you can solve the problem by doing the following:
- Uninstall the Pdx-Unlimiter in the control panel (This will not delete any configuration or savegame data)
- Download the latest installer and install it at the location you want

Any further updates should then be installed in the same directory.

**Comment by crschnick** [comment] 2021-03-02 14:58
I just released a new launcher update.
Since this should be fixed, it should install into your custom directory.

**Comment by crschnick** [comment] 2021-04-02 14:36
Should be fixed, so I am closing this

**Closed by crschnick** 2021-04-02 14:36 UTC
Labels: bug
