### ISSUE TITLE
my file is too big

### ISSUE THREAD

**Issue by redxkiller45** [crschnick/pdx_unlimiter#99] opened 2023-03-29 13:40 UTC
what do i do?

**Comment by crschnick** [comment] 2023-03-29 13:42
I have seen that issue a couple of times. It is usually caused by a mod or a bug in the game firing a massive amount of events are something similar. Other people that had that issue solved it by disabling the mod that caused them.

**Comment by crschnick** [comment] 2023-04-18 04:51
Closing this for now, I hope the issue has been resolved.

**Closed by crschnick** 2023-04-18 04:51 UTC
