### ISSUE TITLE
App configuration unavailable when attempting to launch from pdx?

### ISSUE THREAD

**Issue by mm04926412** [crschnick/pdx_unlimiter#67] opened 2021-05-25 16:20 UTC
I'm having trouble launching eu4 from the app as the launch button just causes steam to say the app configuration is unavailable. In addition to this if I launch a save via the continue game button often all my dlc gets disabled. Is there anything I might be doing that is causing this?

**Comment by crschnick** [comment] 2021-05-25 16:27
I had this issue as well sometimes, it is caused by the Steam servers having issues.

![image](https://user-images.githubusercontent.com/72509152/119533467-28a37380-bd86-11eb-9850-352fba4e42c0.png)

However, the Continue Game button should automatically enable all required mods and dlcs. If it is not doing that for you, can you give me some additional information about that? Is it warning you that some dlcs are missing when clicking `Continue Game`?

**Comment by mm04926412** [comment] 2021-05-25 16:33
It doesn't happen every time, but if it does happen the game goes to the main menu because it cant load the dlc enabled save and the game is running in pure vanilla with no enabled dlc or mods.

**Comment by crschnick** [comment] 2021-05-25 16:48
That might also be caused by Steam having issues:

![image](https://user-images.githubusercontent.com/72509152/119535986-dfa0ee80-bd88-11eb-88b0-29aaa55839d6.png)

The Paradox Launcher seems to not be able to verify whether the dlc is owned and disables it

**Comment by crschnick** [comment] 2021-05-26 07:38
Ok, I found the issue: The new 1.31.4 beta somehow changed the Steam AppID of all eu4 1.31 versions. This is probably not intended by Paradox and also breaks their own Launcher and DLCs. This will also prevent launching eu4 from the Pdx-Unlimiter.

How to fix:
- Either goto your SteamApps directory (something like `C:\Program Files (x86)\Steam\steamapps\common\Europa Universalis IV`) and change the steam_appid.txt to `236850`
- Alternatively, you can use the `Export` button for a savegame and then start eu4 manually

**Comment by crschnick** [comment] 2021-05-26 10:35
I will hopefully have the time to fix this problem this weekend

**Comment by mm04926412** [comment] 2021-05-27 17:36
Is there no option to just go to the main menu and export a save game btw? I find it odd I have to exit just to export?

**Comment by crschnick** [comment] 2021-05-28 01:35
In theory you should be able to select `Start in Launcher` to export it and start the game launcher to easily go to the main menu. But right now, since starting the launcher and the game doesn't work correctly, `Export` is the only button that works.
I will also add the ability to export a savegame while a game is running, I didn't really think about that case

**Comment by mm04926412** [comment] 2021-05-28 15:10
btw if you're taking suggestions a "branch" button that moves an imported save to a "child" branch so you can jump off at key decision points and see how things turn out. Like basically the structure of git but for the saves would be amazing and I was thinking git could possibly just be wrapped directly?

Also would you be willing to add the ability to sort the imported saves by "last modified" instead of just the in game date? It gets hard to determine which "early years" saves are recent and which ones are the old ones.

I'd also offer to help on this project myself if I get the time. My codings not great though lol!

**Comment by crschnick** [comment] 2021-05-29 14:13
Can you try to launch your savegame again with the new update I just released? It should be fixed.

About your suggestions, all of them are already on my internal TODO list. It's just that branching is very compliated to manage, and the implementation would be very game specific. I will also think about the ordering.

By reporting issues and making suggestions you already help a lot!

**Comment by mm04926412** [comment] 2021-05-29 14:25
I was thinking you could directly use git for the branching and storage system and front end it?

I'm currently trying to manage my save games with git and its actually pretty useful and powerful.

**Comment by crschnick** [comment] 2021-05-30 06:14
That would be a lot of work. I will soon push an update that will add branching in a more lightweight way.

**Comment by crschnick** [comment] 2022-02-09 02:13
I will close this for now. I didn't come around to finish the branching experiments I did as they were more complex then expected.

However, it is still on my TODO list

**Closed by crschnick** 2022-02-09 02:13 UTC
Labels: bug, eu4
